# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '1.0.$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build projects
  jobs:  
  - job: Build
    displayName: Build projects
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
- stage: Test
  displayName: Run unit tests
  jobs:  
  - job: Test
    displayName: Run unit tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
- stage: Build_Artifact
  displayName: Build container image
  jobs:  
  - job: Build_Artifact
    displayName: Build container image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ProductService/Dockerfile'
        tags: |
          $(tag)
- stage: Push_Artifact
  displayName: Push container image
  jobs:  
  - job: Push_Artifact
    displayName: Push container image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'ProductService'
        command: 'push'
        tags: '$(tag)'